Repository depromeet/globber-server, pull requests merged in 2025-09, with the labels that each got.

#6 이슈템플릿 & PR템플릿 추가.
  .github/ISSUE_TEMPLATE/chore.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/deploy.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🧹 chore

#4 [CHORE] Testcontainers 기반 Postgres/Redis 통합 테스트 환경 구축
  .github/workflows/ci-test.yml
  build.gradle
  docker-compose-dev.yml
  docker-compose-prod.yml
  promtail-config-dev.yml
  promtail-config-prod.yml
  src/test/java/backend/globber/support/PostgresIntegrationTest.java
  src/test/java/backend/globber/support/PostgresTestConfig.java
  src/test/java/backend/globber/support/RedisIntegrationTest.java
  src/test/java/backend/globber/support/RedisTestConfig.java
Labels: 🧹 chore

#14 [CHORE] 불필요한 파일 제거
  docker-compose-dev.yml
  docker-compose-prod.yml
  promtail-config-dev.yml
  promtail-config-prod.yml
  src/main/resources/application-local.yml
Labels: 🧹 chore

#31 [REFACTOR] 네이밍 변경
  src/main/java/backend/globber/membertravel/controller/GlobeController.java
Labels: 🛠️ refactor

#29 [FEATURE] JPA auditing 활성화 어노테이션 추가
  src/main/java/backend/globber/GlobberApplication.java
  src/test/java/backend/globber/support/RedisIntegrationTest.java
Labels: ✨ feat

#37 [FIX] 리다이렉트 URI 디코딩 로직 추가
  src/main/java/backend/globber/auth/util/auth_filter/OauthUtil.java
Labels: ✨ feat

#44 [REFACTOR] redirect uri 변경
  src/main/java/backend/globber/auth/util/auth_filter/OauthUtil.java
Labels: 🛠️ refactor
